{% set name = "tocount" %}
{% set version = "0.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/tocount
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.7
    run:
        - python >=3.7
about:
    home: https://github.com/openscilab/tocount
    license: MIT
    license_family: MIT
    summary: ToCount: Lightweight Token Estimator
    description: |
	    ToCount is a lightweight and extensible Python library for estimating token counts from text inputs using both rule-based and machine learning methods.
        Designed for flexibility, speed, and accuracy, ToCount provides a unified interface for different estimation strategies, making it ideal for tasks like prompt analysis,
        token budgeting, and optimizing interactions with token-based systems.
        
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/tocount
extra:
    recipe-maintainers:
        - sadrasabouri
        - sepandhaghighi
