name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

env:
  TEST_PYTHON_VERSION: 3.9
  TEST_OS: 'ubuntu-22.04'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macOS-13]
        python-version: [3.7, 3.8, 3.9, 3.10.5, 3.11.0, 3.12.0, 3.13.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test requirements installation
        run: |
          pip install -r dev-requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest . --cov=tocount --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.python-version == env.TEST_PYTHON_VERSION && matrix.os == env.TEST_OS
      - name: Vulture, Bandit and Pydocstyle tests
        run: |
          python -m vulture tocount/ setup.py --min-confidence 80 --sort-by-size
          python -m bandit -r tocount
          python -m pydocstyle tocount
      - name: Version check
        run: |
          python otherfiles/version_check.py
        if: matrix.python-version == env.TEST_PYTHON_VERSION
